In [ ]:
import torch
random_tensor=torch.rand(4,4,)
random_tensor


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])

In [ ]:
print(f"Data type of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is stored on: {random_tensor.device}")

Data type of tensor: torch.float32
Shape of tensor: torch.Size([4, 4])
Device tensor is stored on: cpu


In [ ]:
random_tensor=torch.tensor([4,4,4,])
random_tensor+20

tensor([24, 24, 24])

In [ ]:
tensor1=torch.ones(3,3)
tensor2=torch.ones(3,3)
torch.matmul(tensor1,tensor2)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [ ]:
torch.matmul

<function torch._VariableFunctionsClass.matmul>

In [ ]:
torch.matmul(tensor_3x3,tensor_3x2)

NameError: name 'tensor_3x3' is not defined

In [ ]:
tensor.shape
tensor_3x3.shape
tensor_3x2.shape

In [ ]:
tensor_3x3.shape


In [ ]:
tensor1 = torch.tensor([[5, 7],
                        [6, 3],
                        [9, 8]], dtype=torch.int32)

tensor2 = torch.tensor([[ 95,  76],
                        [114,  88],
                        [171, 144]], dtype=torch.int32)

tensor2_T = tensor2.T
torch.matmul(tensor1, tensor2_T)

In [ ]:
import torch

x= torch.arange(0,100,10)
x

In [ ]:
x.argmax ()

In [ ]:
x.argmin()

In [ ]:
x.

In [ ]:
x=torch.arange(1,10,)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.shape

torch.Size([9])

In [ ]:
torch.reshape(x,(9,1))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x_reshaped=x.reshape(1,9)
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.size()

torch.Size([1, 9])

In [ ]:
z=x_reshaped.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:,0]=3
z,x_reshaped

(tensor([[3, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([[3, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[3, 2, 3, 4, 5, 6, 7, 8, 9],
        [3, 2, 3, 4, 5, 6, 7, 8, 9],
        [3, 2, 3, 4, 5, 6, 7, 8, 9],
        [3, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
x_reshaped.squeeze()


tensor([3, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_reshaped.squeeze().shape


torch.Size([9])

In [ ]:
x_unsqueezed_back=x_reshaped.squeeze().unsqueeze(dim=2)
x_unsqueezed_back.shape

torch.Size([1, 9])

In [ ]:
import torch

# Create a sample tensor with 3 dimensions
tensor_3d = torch.randn(2, 3, 4)
print("Original tensor_3d:")
print(tensor_3d)
print("Original shape:", tensor_3d.shape)

Original tensor_3d:
tensor([[[ 1.6423, -0.1596, -0.4974,  0.4396],
         [-0.7581,  1.0783,  0.8008,  1.6806],
         [ 0.0349,  0.3211,  1.5736, -0.8455]],

        [[ 1.3123,  0.6872, -1.0892, -0.3553],
         [-1.4181,  0.8963,  0.0499,  2.2667],
         [ 1.1790, -0.4345, -1.3864, -1.2862]]])
Original shape: torch.Size([2, 3, 4])


In [ ]:
tensor_3d.permute(2, 1, 0)

tensor([[[ 1.6423,  1.3123],
         [-0.7581, -1.4181],
         [ 0.0349,  1.1790]],

        [[-0.1596,  0.6872],
         [ 1.0783,  0.8963],
         [ 0.3211, -0.4345]],

        [[-0.4974, -1.0892],
         [ 0.8008,  0.0499],
         [ 1.5736, -1.3864]],

        [[ 0.4396, -0.3553],
         [ 1.6806,  2.2667],
         [-0.8455, -1.2862]]])

In [ ]:
# Permute the dimensions: change order from (dim0, dim1, dim2) to (dim2, dim1, dim0)
tensor_permuted = tensor_3d.permute(2, 1, 0)
print("\nTensor after permuting (2, 1, 0):")
print(tensor_permuted)
print("Permuted shape:", tensor_permuted.shape)


Tensor after permuting (2, 1, 0):
tensor([[[ 1.6423,  1.3123],
         [-0.7581, -1.4181],
         [ 0.0349,  1.1790]],

        [[-0.1596,  0.6872],
         [ 1.0783,  0.8963],
         [ 0.3211, -0.4345]],

        [[-0.4974, -1.0892],
         [ 0.8008,  0.0499],
         [ 1.5736, -1.3864]],

        [[ 0.4396, -0.3553],
         [ 1.6806,  2.2667],
         [-0.8455, -1.2862]]])
Permuted shape: torch.Size([4, 3, 2])


In [ ]:
# Another example: change order from (dim0, dim1, dim2) to (dim1, dim2, dim0)
tensor_permuted_2 = tensor_3d.permute(1, 2, 0)
print("\nTensor after permuting (1, 2, 0):")
print(tensor_permuted_2)
print("Permuted shape:", tensor_permuted_2.shape)


Tensor after permuting (1, 2, 0):
tensor([[[ 1.6423,  1.3123],
         [-0.1596,  0.6872],
         [-0.4974, -1.0892],
         [ 0.4396, -0.3553]],

        [[-0.7581, -1.4181],
         [ 1.0783,  0.8963],
         [ 0.8008,  0.0499],
         [ 1.6806,  2.2667]],

        [[ 0.0349,  1.1790],
         [ 0.3211, -0.4345],
         [ 1.5736, -1.3864],
         [-0.8455, -1.2862]]])
Permuted shape: torch.Size([3, 4, 2])


In [ ]:
x=torch.randn(224,224,3)
x.shape

torch.Size([224, 224, 3])

In [ ]:
x_permuted=x.permute(0,2,1)
x_permuted.shape

torch.Size([224, 3, 224])

In [ ]:
x=torch.randn(224,224,3)
x

tensor([[[ 0.8753,  0.6270,  1.2734],
         [-0.4317,  0.0351, -1.8916],
         [-0.0585,  0.2234,  1.7731],
         ...,
         [-1.4994, -0.2761,  1.4278],
         [-0.8500, -0.2971, -1.5458],
         [-1.4648, -1.3181, -0.1845]],

        [[ 0.1646, -0.6821,  0.1788],
         [-1.1683,  0.8050,  0.4251],
         [ 1.8971, -1.1089,  0.2396],
         ...,
         [ 0.1628,  0.2452,  0.7142],
         [ 0.6877,  0.7622,  0.0220],
         [ 0.0385,  0.0850,  1.1395]],

        [[-0.4402,  0.2477, -1.6169],
         [-0.2962, -0.2180, -1.2748],
         [ 0.5469, -0.2044,  2.4227],
         ...,
         [-0.8204,  0.8003,  0.6790],
         [-1.0750, -0.7220, -0.3086],
         [-0.8037,  0.3648, -0.1214]],

        ...,

        [[-0.6105, -0.6864, -0.4670],
         [-0.2492,  0.5010,  2.2991],
         [-0.9702,  0.2380, -0.0775],
         ...,
         [-0.3242, -0.0737,  2.6557],
         [-0.0206,  0.7179, -1.4317],
         [ 1.5267, -0.5320,  0.3177]],

        [[

In [ ]:
# imdexing
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

Notice how the elements themselves remain the same, but their position is now determined by the new order of dimensions. The numbers in `permute()` correspond to the original dimension indices.